### PR TITLE
Show common environment when no environment provided

### PR DESCRIPTION
**Pull request by janelletavares**
# Description of change

*A brief description of the change, what it is and why it was made.*

Fixes https://github.com/meroxa/cli/issues/229
Fixes https://github.com/meroxa/cli/issues/230

# Type of change

- [ ]  New feature
- [X ]  Bug fix
- [ ]  Refactor
- [ ]  Documentation

# How was this tested?

- [ X]  Unit Tests
- [ ]  Tested in staging

# Demo

**Before this pull-request**

$ m pipeline describe jtnewname
  UUID:   9b16822d-a546-4cf8-be6b-300471f6dab2 
    ID:   2961                                 
  Name:   jtnewname                            
 State:   Healthy                              

$ m connector describe mongodb-connector
        UUID:   a69160c7-0014-40e7-a953-fe5042876ebe        
          ID:   5532                                        
        Name:   mongodb-connector                           
        Type:   debezium-mongo-source                       
     Streams:   (output) resource-6633-459461.meroxa.meroxa 
       State:   pending                                     
    Pipeline:   jtest                                       
 Environment:   janelle-dec9     

**After this pull-request**                     

$ m pipeline describe jtnewname
             UUID:   9b16822d-a546-4cf8-be6b-300471f6dab2 
               ID:   2961                                 
             Name:   jtnewname                            
 Environment Name:   common                               
            State:   Healthy                              

$ m connector describe mongodb-connector
             UUID:   91ee0a06-436f-4c7f-a459-0a920c623ed0        
               ID:   5533                                        
             Name:   mongodb-connector                           
             Type:   debezium-mongo-source                       
          Streams:   (output) resource-6633-666758.meroxa.meroxa 
            State:   running                                     
         Pipeline:   jtest                                       
 Environment UUID:   514280e6-6825-4728-b98a-cc4a24cb38aa        
 Environment Name:   janelle-dec9 

# Additional references

*Any additional links (if appropriate)*

# Documentation updated

*Make sure that our [documentation](https://docs.meroxa.com/) is accordingly updated when necessary.*

You can do that by opening a pull-request to our (🔒 private, for now) repository: https://github.com/meroxa/meroxa-docs.

✨ In the future, there will be a GitHub action taking care of these updates automatically. ✨

*Provide PR link:*

### CODE REVIEW

**Comment by raulb** [comment]
@janelletavares this was by design. Only when listing environments, we're showing "common" if no environments is not set. For specific environments, we mentioned we wouldn't show environments unless is present. Maybe we changed that decision?

**Comment by janelletavares** [comment]
> @janelletavares this was by design. Only when listing environments, we're showing "common" if no environments is not set. For specific environments, we mentioned we wouldn't show environments unless is present. Maybe we changed that decision?

Ah, I was not aware of that.  It came up in standup that more consistency would be better. Maybe just the changes for issue #229 and not for #230 then.

**Comment by raulb** [comment]
> Ah, I was not aware of that. It came up in standup that more consistency would be better. Maybe just the changes for issue #229 and not for #230 then.

@janelletavares If that's the case, go for it! It sounds like your information is more up to date.

**Review by anna-cross — APPROVED** [review]
Changes approved! Tested them locally via CLI , and got the same results ! :)

**Review by dianadoherty — APPROVED** [review]

**Pull request merged**
