### PR TITLE
Only create the application if it doesn't already exist with the give…

### PR DESCRIPTION
**Pull request by janelletavares**
…n name

## Description of change
allow this logic to slowly make its way into the turbine libraries

Fixes https://github.com/meroxa/turbine-project/issues/125

## Type of change

- [x]  New feature
- [ ]  Bug fix
- [ ]  Refactor
- [ ]  Documentation

## How was this tested?

- [ ]  Unit Tests
- [x]  Tested in staging

## Demo
Screenshot from 2022-03-31 13-30-48

same logic applied to something easier to test HAH

### CODE REVIEW

**Review by ericcheatham — APPROVED** [review]
🎉

**Review by raulb — CHANGES_REQUESTED** [review]
@janelletavares if the app was already created, we should double check before returning that the pipeline associated is the one that's intended, otherwise it'd seemed like it worked, when it shouldn't have.

I was thinking we could fetch for application before creating and then comparing pipeline uuid there (if it exists). This, only until each turbine language implements their own app creation. 

What do you think?

**Comment by janelletavares** [comment]
> @janelletavares if the app was already created, we should double check before returning that the pipeline associated is the one that's intended, otherwise it'd seemed like it worked, when it shouldn't have.
> 
> I was thinking we could fetch for application before creating and then comparing pipeline uuid there (if it exists). This, only until each turbine language implements their own app creation.
> 
> What do you think?

double  checking seems very reasonable.  will whip that up.

**Comment by janelletavares** [comment]
small meroxa-go change was needed https://github.com/meroxa/meroxa-go/pull/108/files

**Review by raulb — APPROVED** [review]

**Pull request merged**
